package:
  name: xyce
  version: 7.4

source:
  git_url: https://github.com/Xyce/Xyce.git
  git_rev: b7bb12d81f11d8b50141262537299b09d64b5565

build:
  number: 3

requirements:
  build:
    - cmake >=3.10.0
    - gcc_linux-64
    - gxx_linux-64
    - gfortran_linux-64
    - mpich
    - suitesparse
    - libblas
    - liblapack
    - glib
    - fftw
    - bison
    - flex
    - trilinos
  host:
    - libblas
    - liblapack
    - xorg-libx11
    - mpich
    - boost-cpp
    - hdf5 * mpi_mpich_*
    - fftw
    - trilinos
  run:
    - mpich
    - boost-cpp
    - suitesparse
    - libblas
    - liblapack
    - fftw
    - trilinos

about:
  home: https://xyce.sandia.gov
  summary: "The Xyce Parallel Electronic Simulator"
  description: |
    Xyce is an open source, SPICE-compatible, high-performance analog circuit
    simulator, capable of solving extremely large circuit problems by
    supporting large-scale parallel computing platforms. It also supports serial
    execution on all common desktop platforms, and small-scale parallel runs on
    Unix-like systems. In addition to analog electronic simulation, Xyce has
    also been used to investigate more general network systems, such as neural
    networks and power grids. In providing an Open Source version of Xyce to the
    external community, Sandia hopes to contribute a robust and modern
    electronic simulator to users and researchers in the field.
