# This recipe is a modified version of conda-eda/magic to install a specific version of magic
# (https://github.com/hdl/conda-eda/tree/master/misc/magic)

package:
  name: magic
  version: 8.3.353

source:
   git_url: git://opencircuitdesign.com/magic
   git_rev: 8.3.353

build:
  number: 0

requirements:
  build:
    - autoconf
    - automake
    - make
    - python
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxau-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxrender-devel') }}  # [linux]    
  host:
    - tk
    - cairo

about:
  home: http://opencircuitdesign.com/magic/
  summary: "Magic VLSI Layout Tool"
  description: |
    Magic is a venerable VLSI layout tool, written in the 1980's at Berkeley by
    John Ousterhout, now famous primarily for writing the scripting interpreter
    language Tcl.
    Due largely in part to its liberal Berkeley open-source license, magic has
    remained popular with universities and small companies.
    The open-source license has allowed VLSI engineers with a bent toward
    programming to implement clever ideas and help magic stay abreast of
    fabrication technology.
    However, it is the well thought-out core algorithms which lend to magic the
    greatest part of its popularity.
    Magic is widely cited as being the easiest tool to use for circuit layout,
    even for people who ultimately rely on commercial tools for their product
    design flow.
