# This recipe is a modified version of conda-eda/netgen to install a specific version of netgen
# (https://github.com/hdl/conda-eda/tree/master/misc/netgen)

package:
  name: netgen
  version: 1.5.253

source:
   git_url: https://github.com/RTimothyEdwards/netgen
   git_rev: 1.5.253

build:
  number: 0

requirements:
  build:
    - autoconf
    - automake
    - make
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxau-devel') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
  host:
    - python
    - tk
  run:
    - python

about:
  home: http://opencircuitdesign.com/netgen/
  summary: "Netlist comparison (LVS) and format manipulation"
  description: |
    Netgen is a tool for comparing netlists, a process known as LVS,
    which stands for \"Layout vs. Schematic\". This is an important
    step in the integrated circuit design flow, ensuring that the
    geometry that has been laid out matches the expected circuit.
    Very small circuits can bypass this step by confirming circuit
    operation through extraction and simulation. Very large digital
    circuits are usually generated by tools from high-level
    descriptions, using compilers that ensure the correct layout
    geometry. The greatest need for LVS is in large analog or
    mixed-signal circuits that cannot be simulated in reasonable
    time. Even for small circuits, LVS can be done much faster than
    simulation, and provides feedback that makes it easier to find
    an error than does a simulation."
